; This configuration file enables configuring OpenPLC capabilities
; when the OpenPLC runtime starts. These capabilities can be configured
; without using the web front end and enable running the OpenPLC runtime
; standalone.
;
; This file must be located in the "etc" folder and must be named
; "config.ini".

; ---------------------------------------------------------
; ---------------------------------------------------------
[logging]
level = info

; ---------------------------------------------------------
; ---------------------------------------------------------
[interactive]
enabled = true

; ---------------------------------------------------------
; ---------------------------------------------------------
[modbusslave]
enabled = true
port = 502
address = 127.0.0.1
binding = sized

; ---------------------------------------------------------
; ---------------------------------------------------------
[modbusmaster]
enabled = false

; ---------------------------------------------------------
; ---------------------------------------------------------
[pstorage]
enabled = false

; ---------------------------------------------------------
; ---------------------------------------------------------
[dnp3s]
enabled = false
